#!/bin/bash

# Deploy contracts to local Hardhat and update frontend/.env.local

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$ROOT_DIR/contracts"
FRONTEND_DIR="$ROOT_DIR/frontend"

echo "=========================================="
echo "Deploying to: Local Hardhat (localhost)"
echo "=========================================="

# Deploy contracts
cd "$CONTRACTS_DIR"
npx hardhat run scripts/deploy.ts --network localhost

# Read deployed addresses
ADDRESSES_FILE="$CONTRACTS_DIR/deployed-addresses.json"
if [ ! -f "$ADDRESSES_FILE" ]; then
  echo "Error: deployed-addresses.json not found"
  exit 1
fi

ORACLE_REGISTRY=$(grep -o '"oracleRegistry": "[^"]*' "$ADDRESSES_FILE" | cut -d'"' -f4)
MARKET_FACTORY=$(grep -o '"marketFactory": "[^"]*' "$ADDRESSES_FILE" | cut -d'"' -f4)

echo ""
echo "Updating frontend/.env.local..."

cat > "$FRONTEND_DIR/.env.local" << EOF
# Auto-generated by deploy-local.sh on $(date -Iseconds)
VITE_DEFAULT_NETWORK=local

# Local Hardhat addresses
VITE_LOCAL_ORACLE_REGISTRY=$ORACLE_REGISTRY
VITE_LOCAL_MARKET_FACTORY=$MARKET_FACTORY

# Testnet addresses (fill in after testnet deployment)
VITE_TESTNET_ORACLE_REGISTRY=
VITE_TESTNET_MARKET_FACTORY=
EOF

echo ""
echo "=========================================="
echo "Deployment complete!"
echo "=========================================="
echo "OracleRegistry: $ORACLE_REGISTRY"
echo "MarketFactory:  $MARKET_FACTORY"
echo "=========================================="
