#!/bin/bash

# Deploy contracts to Sapphire Testnet and update frontend env files

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$ROOT_DIR/contracts"
FRONTEND_DIR="$ROOT_DIR/frontend"

# Check for private key
if [ -z "$PRIVATE_KEY" ]; then
  echo "Error: PRIVATE_KEY environment variable is required"
  echo ""
  echo "Usage: PRIVATE_KEY=your-key ./scripts/deploy-testnet.sh"
  exit 1
fi

echo "=========================================="
echo "Deploying to: Sapphire Testnet"
echo "=========================================="

# Deploy contracts
cd "$CONTRACTS_DIR"
npx hardhat run scripts/deploy.ts --network sapphire_testnet

# Read deployed addresses
ADDRESSES_FILE="$CONTRACTS_DIR/deployed-addresses.json"
if [ ! -f "$ADDRESSES_FILE" ]; then
  echo "Error: deployed-addresses.json not found"
  exit 1
fi

ORACLE_REGISTRY=$(grep -o '"oracleRegistry": "[^"]*' "$ADDRESSES_FILE" | cut -d'"' -f4)
MARKET_FACTORY=$(grep -o '"marketFactory": "[^"]*' "$ADDRESSES_FILE" | cut -d'"' -f4)

echo ""
echo "Updating frontend env files..."

# Create/update .env.production for Vercel
cat > "$FRONTEND_DIR/.env.production" << EOF
# Auto-generated by deploy-testnet.sh on $(date -Iseconds)
VITE_DEFAULT_NETWORK=testnet

# Sapphire Testnet addresses
VITE_TESTNET_ORACLE_REGISTRY=$ORACLE_REGISTRY
VITE_TESTNET_MARKET_FACTORY=$MARKET_FACTORY
EOF

echo "Updated: .env.production"

# Also update .env.local with testnet addresses if it exists
LOCAL_ENV="$FRONTEND_DIR/.env.local"
if [ -f "$LOCAL_ENV" ]; then
  if grep -q "VITE_TESTNET_ORACLE_REGISTRY" "$LOCAL_ENV"; then
    sed -i '' "s|VITE_TESTNET_ORACLE_REGISTRY=.*|VITE_TESTNET_ORACLE_REGISTRY=$ORACLE_REGISTRY|" "$LOCAL_ENV"
  else
    echo "VITE_TESTNET_ORACLE_REGISTRY=$ORACLE_REGISTRY" >> "$LOCAL_ENV"
  fi

  if grep -q "VITE_TESTNET_MARKET_FACTORY" "$LOCAL_ENV"; then
    sed -i '' "s|VITE_TESTNET_MARKET_FACTORY=.*|VITE_TESTNET_MARKET_FACTORY=$MARKET_FACTORY|" "$LOCAL_ENV"
  else
    echo "VITE_TESTNET_MARKET_FACTORY=$MARKET_FACTORY" >> "$LOCAL_ENV"
  fi
  echo "Updated: .env.local (testnet addresses)"
fi

echo ""
echo "=========================================="
echo "Deployment complete!"
echo "=========================================="
echo "OracleRegistry: $ORACLE_REGISTRY"
echo "MarketFactory:  $MARKET_FACTORY"
echo "=========================================="
echo ""
echo "Next steps for Vercel:"
echo "  1. Add these env vars in Vercel dashboard:"
echo "     VITE_DEFAULT_NETWORK=testnet"
echo "     VITE_TESTNET_ORACLE_REGISTRY=$ORACLE_REGISTRY"
echo "     VITE_TESTNET_MARKET_FACTORY=$MARKET_FACTORY"
echo "  2. Redeploy on Vercel"
